#!/bin/bash

jobName=hgtest2
prepid=JME-RunIIFall18wmLHEGS-00020
analysis=CMS_2016_I1459051

nJobs=1
nEv=50


if [ "$#" -eq 5 ]
then
jobName=$1
prepid=$2
analysis=$3

nJobs=$4
nEv=$5
echo $jobName  $prepid  $analysis  $nJobs  $nEv
fi

#exit 0

rm -rf farm/$jobName

mkdir -p farm/$jobName/logs
mkdir -p farm/$jobName/histos
cp runMC.sh farm/$jobName

tag=`basename $jobName`
condor_submit -batch-name $tag nJobs=$nJobs jobName=$jobName prepid=$prepid analysis=$analysis nEv=$nEv runRivet.submit
